Default: &defaults
  database: ptestnosandb.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ptestnosandb_test.sqlite3
  <<: *defaults

Staging:
  database: ptestnosandb_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ptestnosandb_production.sqlite3
  poolsize: 100
  <<: *defaults
